### ISSUE TITLE
`TypeError: keys$1 is not a function`

### ISSUE THREAD

**Issue by amcdnl** [webNeat/ctrl-keys#8]
In my project ( reablocks.dev ), we use this library for the command palette. Everything works great except when a user tries to use the package with NextJS. I get the error below:

```
TypeError: keys$1 is not a function
```

Reference: https://github.com/reaviz/reablocks/blob/master/src/elements/CommandPalette/CommandPaletteInput/CommandPaletteInput.tsx#L14

I think it might be related to `exports` in the `package.json` file. Here is an example of ours: https://github.com/reaviz/reablocks/blob/master/package.json#L27-L32 but this is just a guess.

**Comment by webNeat** [comment]
Hello @amcdnl 

Thank you for reporting this bug, I will take a look at it.

**Comment by webNeat** [comment]
Hello @amcdnl 

I created this repo as a try to reproduce the error https://github.com/webNeat/ctrl-keys-reablocks-next-demo

But I didn't get the error above, am I missing something? can you please provide a simple repo that reproduces the issue so that I can investigate further?

**Comment by amcdnl** [comment]
Appreciate you taking the time to make a repo case. Let me see if I can track it down better.

**Comment by SerhiiTsybulskyi** [comment]
Hello @webNeat, I have the same issue but with different steps to reproduce.
I've prepared code sandbox to reproduces the issue:  [Link](https://codesandbox.io/p/devbox/ctrl-keys-issue-8w4xdg?file=%2Fsrc%2Fexample.spec.ts%3A12%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxlgss1000073b6jx3yraxvj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxlgss1000023b6jg80o42i4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxlgss1000043b6jczlfq4d3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxlgss1000063b6jbkksf43b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxlgss1000023b6jg80o42i4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlgss1000013b6jiobj1isn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxlhhkes00023b6j5zk81lqg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fexample.spec.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxlgss1000023b6jg80o42i4%2522%252C%2522activeTabId%2522%253A%2522clxlhhkes00023b6j5zk81lqg%2522%257D%252C%2522clxlgss1000063b6jbkksf43b%2522%253A%257B%2522id%2522%253A%2522clxlgss1000063b6jbkksf43b%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clxlhoqzb007d3b6j3nn6kfj8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxlhoqzb007d3b6j3nn6kfj8%2522%257D%252C%2522clxlgss1000043b6jczlfq4d3%2522%253A%257B%2522id%2522%253A%2522clxlgss1000043b6jczlfq4d3%2522%252C%2522activeTabId%2522%253A%2522clxlh15xb00913b6jw3sp0wsl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlh15xb00913b6jw3sp0wsl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxlh160q00qtdcip1fwl72t2%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

You need run `pnpm i` and than `pnpm run test`

![Screenshot 2024-06-19 at 10 25 28](https://github.com/webNeat/ctrl-keys/assets/5399389/c8ef0e8f-ea72-4914-af8d-79a0a076446c)

**Comment by webNeat** [comment]
Hello @SerhiiTsybulskyi, Thank you for reproducing the issue, it seems like a problem with the way Vitest loads modules. I will investigate further and try to fix it soon.

**Comment by amcdnl** [comment]
@webNeat - I would check out the exports code I referenced above. It might be the solution.

**Comment by webNeat** [comment]
Hello @amcdnl 

I applied your suggested solution and it seems to fix the issue. I released v1.0.3, please try it and let me know if it solves the issue.
